config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :laboratories
  resources :receptionists
  resources :doctors
  resources :patients
  resources :tubes
  resources :exams
  resources :companies
  resources :quotations
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'home#index'

  devise_for :users, controller: { registrations: "devise/registrations"}

  get '/home/reset_data' => 'home#reset_data'

  resources :companies do
    resources :quotations
  end

  resources :exams do
    member do
      get 'get_values'
    end
  end

  resources :quotations do
    collection do
      post 'search'
    end
  end

  resources :orders do
    collection do
      post 'search'
    end
  end

  resources :users do
    collection do
      post 'create_seller'
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user!, except: [:reset_data]
  def index
  	# if user_signed_in?
  	# 	# @companies = Company.where(:user_id => current_user.id)
   #    @search = Company.search(params[:q])
  	# 	@companies = @search.result.order(:created_at).reverse_order.page(params[:page]).per(10)
  	# else
  	# 	redirect_to new_user_session_path
  	# end

    #Admin
    @admin_pen_quotations = Order.where(:paid => true, :pdf_upload => true).order(:created_at).reverse_order
     
    @patients = Patient.all.order(:created_at).reverse_order.limit(12)
    
    @orders = Order.all.order(:created_at).reverse_order
    #num of months to show
    num_months = 6
    # Approved Quotations
    @app_quotations = @orders.approved
    @app_months = get_last_months(@app_quotations, num_months)
    # Pendig Quotations
    @pen_quotations = @orders.pendig
    @pen_months = get_last_months(@pen_quotations, num_months)

    # Reject Quotations
    @rec_quotations = @orders.registered
    @rec_months = get_last_months(@rec_quotations, num_months)

    # User
    # @u_months = []
    # users = User.all.where(:rol => 1)
    # users.each do |user|
    #   @u_months << get_last_months_by_user(@app_quotations, num_months, user)
    # end
    
  end

  def reset_data
    require 'csv'
    # Clear database
    Rails.application.eager_load!
    ActiveRecord::Base.descendants.each { |c| c.delete_all unless c == ActiveRecord::SchemaMigration  }

    # conn = ActiveRecord::Base.connection
    # tables = ActiveRecord::Base.connection.tables
    # tables.each { |t| conn.execute("TRUNCATE #{t}") }


    # ActiveRecord::Base.connection.tables.each do |t|
    #   ActiveRecord::Base.connection.reset_pk_sequence!(t)
    # end
    

    # ActiveRecord::Base.connection.reset_pk_sequence!("users")
    # ActiveRecord::Base.connection.reset_pk_sequence!("companies")
    # ActiveRecord::Base.connection.reset_pk_sequence!("quotations")
    # ActiveRecord::Base.connection.reset_pk_sequence!("quotation_items")
    # ActiveRecord::Base.connection.reset_pk_sequence!("exams")
    # ActiveRecord::Base.connection.reset_pk_sequence!("exam_updates")
    
    # Add patients
    datafile = Rails.root + 'db/pacientes.csv'
    CSV.foreach(datafile, headers: true) do |row|
      patient = Patient.where(:ci => row[0]).last
      unless patient.present?
        u = Patient.new
        u.ci = row[0]
        u.name  = row[1]
        u.last_name = row[2]
        u.gener = row[3]
        u.age = row[4]
        u.phone = row[5]
        u.save(:validate => false)
      end
    end

    # # Add users
    datafile = Rails.root + 'db/usuarios.csv'
    CSV.foreach(datafile, headers: true) do |row|
      user = User.where(:login => row[0]).last
      unless user.present?
        u = User.new
        u.login = row[0]
        u.email = row[1]
        u.name  = row[2]
        u.password = "123456"
        u.password_confirmation = "123456"
        u.rol = row[3]
        u.save
      end
    end

    datafile = Rails.root + 'db/doctores.csv'
    CSV.foreach(datafile, headers: true) do |row|
      user = Doctor.where(:login => row[0]).last
      unless user.present?
        u = Doctor.new
        u.login = row[0]
        u.email = row[1]
        u.name  = row[2]
        u.password = "123456"
        u.password_confirmation = "123456"
        u.rol = row[3]
        u.speciality = row[3]
        u.save
      end
    end

    datafile = Rails.root + 'db/recepcionistas.csv'
    CSV.foreach(datafile, headers: true) do |row|
      user = Receptionist.where(:login => row[0]).last
      unless user.present?
        u = Receptionist.new
        u.login = row[0]
        u.email = row[1]
        u.name  = row[2]
        u.password = "123456"
        u.password_confirmation = "123456"
        u.rol = row[3]
        u.save
      end
    end

    datafile = Rails.root + 'db/laboratoristas.csv'
    CSV.foreach(datafile, headers: true) do |row|
      user = Laboratory.where(:login => row[0]).last
      unless user.present?
        u = Laboratory.new
        u.login = row[0]
        u.email = row[1]
        u.name  = row[2]
        u.password = "123456"
        u.password_confirmation = "123456"
        u.rol = row[3]
        u.save
      end
    end

    

    # # Add Companies
    # datafile = Rails.root + 'db/empresas.csv'
    # CSV.foreach(datafile, headers: true) do |row|
    #   company = Company.where(:name => row[0]).last
    #   unless company.present?
    #     c = Company.new
    #     c.name = row[0]
    #     c.ruc = row[1]
    #     c.direcction = row[2]
    #     c.sector = row[3]
    #     c.contact_name = row[4]
    #     c.contact_email = row[5]
    #     c.doctor_name = row[6]
    #     c.doctor_email = row[7]
    #     c.billing_name = row[8]
    #     c.billing_email = row[9]
    #     c.user_id = row[10]
    #     c.save
    #   end
    # end

    # Add tubes
    datafile = Rails.root + 'db/tubos.csv'
    CSV.foreach(datafile, headers: true) do |row|
      tube = Tube.where(:name => row[0]).last
      unless tube.present?
        e = Tube.new
        e.code = row[0]
        e.name = row[1]
        e.price = row[2]
        e.save
      end
    end

    # Add examenes
    datafile = Rails.root + 'db/examenes.csv'
    i = 1
    CSV.foreach(datafile, headers: true) do |row|
      exam = Exam.where(:name => row[0]).last
      unless exam.present?
        e = Exam.new
        e.code = row[0]
        e.name = row[1]
        e.activated = row[2]
        e.tube_id = i
        e.save
        i = i + 1
      end
    end

    # # Add Quotarions
    # datafile = Rails.root + 'db/quotations.csv'
    # CSV.foreach(datafile, headers: true) do |row|

    # Add Quotarions
    datafile = Rails.root + 'db/quotations.csv'
    CSV.foreach(datafile, headers: true) do |row|

      q = Quotation.new
      q.description = row[1]
      q.exam_number = 1
      q.city_total = row[3].present? ? row[3].to_d : 0
      q.province_total = row[4].present? ? row[4].to_d : 0
      q.m_units_total = row[5].present? ? row[5].to_d : 0
      q.company_id = 1
      q.total_users = 1
      q.approved = rand(0..1) == 1 ? true : false
      q.rejected = rand(0..1) == 1 ? true : false
      q.created_at = rand((Time.now.to_date - 6.months)..Time.now.to_date)
      q.date = rand((Time.now.to_date - 6.months)..Time.now.to_date)

      if q.approved
        q.date_approved = q.created_at
        q.user_appoved_id = 2
      end
      Rails.logger.info "=====save ====> #{q.save}"
      Rails.logger.info "=====errors ====> #{q.errors.full_messages}"
    end

    redirect_to root_path, alert: "Base de datos cargada"


  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_quotation_row.html.erb
<%- class_content = order.paid ? "content-block approved" : "content-block pending" %>
<div class="<%= class_content%>">
  <div class="row">
    <div class="small-8 medium-9 large-9 columns ">
      <strong>
        <%= link_to order.patient.full_name, order_path(order.patient.id,order), :class => "description" %>  
      </strong>
    </div>
    <div class="small-4 medium-3 large-3 columns text-right color-grey">
      <%= time_ago_in_words(order.created_at)%>
    </div>
    
  </div>

  <div class="row info">
    <div class="medium-6 large-6 columns">
      
      <div class="row">
        <div class="medium-6 large-6 columns"><strong>Fecha: </strong></div>
        <div class="medium-6 large-6 columns"><%= order.date.strftime(@date_format)%></div>
      </div> 

      <div class="row">
        <div class="medium-6 large-6 columns"><strong>CI Paciente: </strong></div>
        <div class="medium-6 large-6 columns"><%= order.patient.ci %></div>
      </div>
    </div>

    <div class="medium-6 large-6 columns">
      
      <div class="row">
        <div class="medium-6 large-6 columns"><strong>Valor: </strong></div>
        <div class="medium-6 large-6 columns"><%= "$" + number_with_precision(order.total, :precision => 2) || 0  %></div>
      </div> 

      <div class="row">
        <div class="medium-6 large-6 columns"><strong>Nro. Examenes: </strong></div>
        <div class="medium-6 large-6 columns"><%= order.exam_number %></div>
      </div>
    </div>
  </div>

  <div class="row info">
    <div class="medium-6 large-6 columns">
      
    </div>

    <div class="medium-6 large-6 columns">
      
      <div class="row">
        <% if current_user.rol == 3 %>
          <div class="small-6 medium-6 large-6 columns"><%= link_to 'Editar', edit_order_path(order), :class => " tiny button" %></div>
          <div class="small-6 medium-6 large-6 columns"><%= link_to 'Eliminar', "/orders/" + order.id.to_s , method: :delete, data: { confirm: 'Esta seguro de eliminar el registro?' }, :class => "destroy tiny button"  %></div>
        <% elsif current_user.rol == 2 %>
          <div class="small-6 medium-6 large-6 columns"></div>
          <div class="small-6 medium-6 large-6 columns"><%= link_to 'Editar', edit_order_path(order), :class => " tiny button" %></div>
        <% else %>
          <div class="small-6 medium-6 large-6 columns"></div>
          <div class="small-6 medium-6 large-6 columns"><%= link_to 'Ver', order_path(order), :class => " tiny button" %></div>
        <% end %>
        
      </div> 

    </div>
  </div>



  

</div>

app/views/home/index.html.erb
<%- content_for :title, 'Resultados' %>
<!-- <div class="second-title">
  <h4>pacientes Registradas</h4>
</div> -->
<div class="box">
  <div class="row">
    <div class="medium-12 large-12 columns">
      <div class="block">
        <div class="title-block">
          <h3><%= "Estadísticas " %> </h3>
        </div>
        <div class="content-block">
          <div class="row ">
            <div class="medium-4 large-4 columns">
              <div class="gray-text-color text-center">
                Ordenes finalizadas
              </div>          
              <canvas id="AppChart" width="200" height="200" bg-color="rgba(108, 188, 49, 0.8)" br-color="#6CBC31">
                <% @app_months.each do |month| %>
                  <div class="param" data="<%= month[1] %>"><%= month[0] %></div>
                <%- end %>
              </canvas>

            </div>

            <div class="medium-4 large-4 columns">
              <div class="gray-text-color text-center">
                Ordenes pendientes de pago

                <canvas id="PenChart" width="200" height="200" bg-color="rgba(238, 117, 99, 0.8)" br-color="#EE7563">
                  <% @pen_months.each do |month| %>
                    <div class="param" data="<%= month[1] %>"><%= month[0] %></div>
                  <%- end %>
                </canvas>
              </div>
            </div>
            <div class="medium-4 large-4 columns">
              <div class="gray-text-color text-center">
                Solicitudes registradas
                <canvas id="RecChart" width="200" height="200" bg-color="rgba(228, 234, 243, 0.8)" br-color="#E4EAF3">
                  <% @rec_months.each do |month| %>
                    <div class="param" data="<%= month[1] %>"><%= month[0] %></div>
                  <%- end %>
                </canvas>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  

  <div class="row">
    <div class="medium-12 large-6 columns">
      <% if current_user.rol == 3 %>
        <div class="block pending">
          <div class="title-block">
            <% if @admin_pen_quotations.count > 10 %>
              <h3><%= "Órdenes pagadas (10/#{@admin_pen_quotations.count}) " %> </h3>
            <% else %>
              <h3><%= "Órdenes pagadas (#{@admin_pen_quotations.count}) " %> </h3>
            <% end %>

          </div>
          <%- if @admin_pen_quotations.any? %>
            <% @admin_pen_quotations.take(10).each do |order| %>
              <%= render 'quotation_row', order: order%>
            <% end %>
          <%- else %>
            <div class="content-block">
              <div class="row">
                <div class="medium-12 large-12 columns">
                  No se encontraron resultados
                </div>
              </div>
            </div>
          <%- end %>
        </div>
      <% else %>  
        <div class="block pending">
          <div class="title-block">

            <% if @pen_quotations.count > 10 %>
              <h3><%= "Órdenes pendientes (10/#{@pen_quotations.count}) " %> </h3>
            <% else %>
              <h3><%= "Órdenes pendientes (#{@pen_quotations.count}) " %> </h3>
            <% end %>

          </div>
          <%- if @pen_quotations.any? %>
            <% @pen_quotations.take(10).each do |quotation| %>
              <%= render 'quotation_row', quotation: quotation%>
            <% end %>
          <%- else %>
            <div class="content-block">
              <div class="row">
                <div class="medium-12 large-12 columns">
                  No se encontraron resultados
                </div>
              </div>
            </div>
          <%- end %>
        </div>
      <% end %>
    </div>
    <div class="medium-12 large-6 columns">
      <div class="block table">
        <div class="title-block">
          <h3>Últimos pacientes (<a href="<%= patients_path %>"> Todos </a>)</h3>
          <div class="right-section">
            <a href=<%= new_patient_path %> class="small success button">Nuevo paciente</a>      
          </div>
        </div>
        <div class="content-block">
          <% if @patients.any? %>
            <table class="responsive">
              <thead>
                <tr>
                  <th style="width: 30%">Nombre</th>
                  <!-- <th style="width: 20%">Ruc</th> -->
                  <th style="width: 10%">CI/Pasaporte</th>
                  <th style="width: 30%">Género</th>
                  <th style="width: 30%">Acciones</th>
                </tr>
              </thead>

              <tbody>
                <% @patients.each do |patient| %>
                  <tr>
                    <td><%= link_to patient.full_name, patient  %></td>
                    <td><%= patient.ci %></td>
                    <td><%= patient.gener_fullname %></td>
                    <td>
                      <%= link_to 'Editar', edit_patient_path(patient.id), :class => current_user.rol == 3 || current_user.rol == 0 ? "tiny button" : "tiny button disabled", :style => "width: 100%;" %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          <% else %> 
            <div class="row" style="margin:20px">
              <div class="medium-12 large-12 columns">
                No se encontraron resultados
              </div>
            </div>
          <% end %>
        </div>
      </div>
      
    </div>
  </div>


</div>

<script>
  function load_chart(id){
    var ctx = $(id);
    var datalabels = [];
    var data = [];
    ctx.children(".param").each(function(i, e){
      datalabels.push($(this).text());
      data.push($(this).attr('data'));
    });
    backgroundColor = ctx.attr('bg-color')
    borderColor = ctx.attr('br-color')
    
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
          labels: datalabels,
          datasets: [{
            label: '# de Órdenes',
            data: data,
            backgroundColor: backgroundColor,
            borderColor: borderColor,
            borderWidth: 1
          }]
        },
        options: {
          scales: {
            yAxes: [{
              ticks: {
                beginAtZero:true,
                stepSize: 1
              }
            }]
          }
        }
    });
  }
  load_chart("#AppChart");
  load_chart("#PenChart");
  load_chart("#RecChart");
</script>