config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :laboratories
  resources :receptionists
  resources :doctors
  resources :patients
  resources :tubes
  resources :exams
  resources :companies
  resources :quotations
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'home#index'

  devise_for :users, controller: { registrations: "devise/registrations"}

  get '/home/reset_data' => 'home#reset_data'

  resources :companies do
    resources :quotations
  end

  resources :exams do
    member do
      get 'get_values'
    end
  end

  resources :quotations do
    collection do
      post 'search'
    end
  end

  resources :orders do
    collection do
      post 'search'
    end
  end

  resources :users do
    collection do
      post 'create_seller'
    end
  end

end

app/models/quotation.rb
class Quotation < ActiveRecord::Base
	#Relations
	belongs_to :company
	has_many :quotation_items, :dependent => :destroy
	accepts_nested_attributes_for :quotation_items, reject_if: proc { |attributes| attributes['exam_id'].blank? ||  attributes['quotation_id'].blank?}, allow_destroy: true

	mount_uploader :pdf, PdfUploader
	# Validations
	validates :description, :presence => true
	validates :total_users, :numericality => { :greater_than => 0}
	# validates_attachment_content_type :pdf, :content_type => /\Aapplication\/pdf/
	
	# validates :quotation_items, length: { minimum: 1, maximum: 1000 }
	validates :exam_number, :numericality => { :greater_than => 0}
	# after_create :send_create_notification

	def total
		province_total = self.provinces ? self.province_total : 0
		m_units_total = self.mobile_units ? self.m_units_total : 0
		total = self.city_total + province_total + m_units_total
	end

	def can_edit(user)
		if user.rol == 1
			if self.approved || self.rejected || self.company.user.id != user.id
				false
			else
				true
			end
		else
			true
		end
	end

	def send_create_notification
    QuotationMailer.new_quotation(self).deliver_now
	end

	class << self

		def approved
			where(:approved => true, :rejected => [false, nil])
		end

		def pendig
			where(:approved => false, :rejected => [false, nil])
		end

		def reject
			where(:rejected => true)
		end

	end
end

app/controllers/quotations_controller.rb
class QuotationsController < ApplicationController
  before_action :authenticate_user! 
  before_action :set_quotation, only: [:show, :edit, :update, :destroy]
  before_action :get_company, except: [:search]
  before_action :can_edit, only: [:edit, :update, :destroy]
  before_action :can_create, only: [:new, :create]
  before_action :get_users, only: [:index, :search]
  skip_before_filter :verify_authenticity_token, :only => [:search]
  

  before_action :get_all_exams, only: [:new, :edit, :create, :update]

  

  # GET /quotations
  # GET /quotations.json
  def index
    @filter_by_company = false
    @quotations = Quotation.order(:created_at).reverse_order
    if @company.present?
      @quotations = @quotations.where(:company_id => @company.id)
      @filter_by_company = true
    else
      if params[:user].present?
        if params[:user] == "all"
          @quotations = @quotations.order(:created_at)
          @quotations_approved = @quotations.where(:approved => true).count
        else
          companies = Company.where(:user_id => params[:user].to_i)
          @filter_user = User.find(params[:user])
          company_ids = companies.map{|c| c.id}
          @quotations = @quotations.where(:company_id => company_ids).order(:created_at)
          @quotations_approved = @quotations.where(:approved => true).count
        end
      else
        companies            = Company.where(:user_id => current_user.id)
        @filter_user         = current_user
        company_ids          = companies.map{|c| c.id}
        @quotations          = @quotations.where(:company_id => company_ids).order(:created_at)
        @quotations_approved = @quotations.where(:approved => true).count
      end 
    end

    @quotations = @quotations.page(params[:page]).per(12)

  end

  # GET /quotations/1
  # GET /quotations/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf do
        pdf = QuotationPdf.new(@quotation)
        send_data pdf.render, filename: "cotizacion_#{@quotation.created_at}.pdf",
                              type: "application/pdf",
                              disposition: "inline"
      end
    end
  end

  # GET /quotations/new
  def new
    @quotation = Quotation.new
    @quotation.total_users = 1
    @quotation.quotation_items.build unless @quotation.quotation_items.any?
  end

  # GET /quotations/1/edit
  def edit
    if @quotation.approved || @quotation.rejected
      if @quotation.approved
        respond_to do |format|
          format.html { redirect_to current_user.rol == 1 ? quotations_path : quotations_path(:user => 'all'), alert: 'Cotización fue aprobada por ' + User.find(@quotation.user_appoved_id).name if @quotation.user_appoved_id }
          format.json { render :show, status: :ok, location: @quotation }
        end
      elsif @quotation.rejected
        respond_to do |format|
          format.html { redirect_to current_user.rol == 1 ? quotations_path : quotations_path(:user => 'all'), alert: 'Cotización fue rechazada' }
          format.json { render :show, status: :ok, location: @quotation }
        end
      end
    else
      @quotation.quotation_items.build unless @quotation.quotation_items.any?
      @company = @quotation.company unless @company.present?
    end
  end

  # POST /quotations
  # POST /quotations.json
  def create
    @quotation = Quotation.new(quotation_params)
    @quotation.company_id = @company.id 
    @quotation.date = Time.now
    if @quotation.approved
      @quotation.date_approved = Time.now
      @quotation.user_appoved_id = current_user.id
    end
    if current_user.rol != 3
      @quotation.approved = false 
    end

    @quotation.exam_number = 0
    num_no_exam = 0
    if quotation_params[:quotation_items_attributes].present?
      quotation_params[:quotation_items_attributes].map{|q| num_no_exam  += 1 if q[1][:exam_id] == '' }
      @quotation.exam_number = quotation_params[:quotation_items_attributes].count - num_no_exam
    end

    respond_to do |format|
      if @quotation.save
        # Save quotation items
        quotation_params[:quotation_items_attributes].each do |item|
          i = QuotationItem.new
          i.quotation_id = @quotation.id
          i.exam_id = item[1][:exam_id]
          i.city_unit = item[1][:city_unit]
          i.province_unit = item[1][:province_unit]
          i.m_units_unit = item[1][:m_units_unit]
          i.save if item[1][:exam_id].present?
        end

        QuotationMailer.new_quotation(@quotation).deliver_now

        format.html { redirect_to current_user.rol == 1 ? quotations_path : quotations_path(:user => 'all'), notice: 'Cotización fue creada con éxito.' }
        format.json { render :show, status: :created, location: @quotation }
      else
        @quotation.quotation_items.build unless @quotation.quotation_items.any?
        # session[:error_quotation] = "Asegurese de ingresar una descripcion y un archivo PDF"
        format.html { render :new }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotations/1
  # PATCH/PUT /quotations/1.json
  def update

    @quotation.exam_number = 0
    num_no_exam = 0
    if quotation_params[:quotation_items_attributes].present?
      quotation_params[:quotation_items_attributes].map{|q| num_no_exam  += 1 if (q[1][:exam_id] == '' || q[1][:_destroy] == '1')}
      @quotation.exam_number = quotation_params[:quotation_items_attributes].count - num_no_exam
    end

    if @quotation.approved || @quotation.rejected
      if @quotation.approved
        respond_to do |format|
          format.html { redirect_to current_user.rol == 1 ? quotations_path : quotations_path(:user => 'all'), alert: 'Cotización ya fue aprobada por ' + User.find(@quotation.user_appoved_id).name if @quotation.user_appoved_id }
          format.json { render :show, status: :ok, location: @quotation }
        end
      elsif @quotation.rejected
        respond_to do |format|
          format.html { redirect_to current_user.rol == 1 ? quotations_path : quotations_path(:user => 'all'), alert: 'Cotización fue rechazada' }
          format.json { render :show, status: :ok, location: @quotation }
        end
      end
    else
      respond_to do |format|
        if @quotation.update(quotation_params)

          if params[:quotation][:approved] == "approved"
            @quotation.approved = true
          elsif params[:quotation][:approved] == "rejected"
            @quotation.rejected = true
          else
            @quotation.approved = false
            @quotation.rejected = false
          end

          if @quotation.approved
            @quotation.rejected = false
            @quotation.date_approved = Time.now
            @quotation.user_appoved_id = current_user.id
            @quotation.save
            QuotationMailer.quotation_approved(@quotation).deliver_now
          else
            @quotation.date_approved = nil
            @quotation.user_appoved_id = nil
            @quotation.rejected = true
            @quotation.save
          end

          if @quotation.rejected
            QuotationMailer.quotation_rejected(@quotation).deliver_now
          end
          # if params[:quotation][:pdf]
          #   @quotation.pdf = params[:quotation][:pdf].read
          # end
          format.html { redirect_to current_user.rol == 1 ? quotations_path : quotations_path(:user => 'all'), notice: 'Cotización fue actualizada con éxito.' }
          format.json { render :show, status: :ok, location: @quotation }
        else
          if @quotation.exam_number == 0
            @quotation.quotation_items = []
            @quotation.quotation_items.build
          end
          format.html { render :edit }
          format.json { render json: @quotation.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /quotations/1
  # DELETE /quotations/1.json
  def destroy
    url = @company.present? ? company_quotations_path(@company) : quotations_path
    if current_user.rol == 3
      @quotation.destroy
      respond_to do |format|
        format.html { redirect_to url, notice: 'Cotización fue eliminada con éxito.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to url, alert: 'Usuario actual no puede eliminar cotización' }
        format.json { head :no_content }
      end
    end
    
  end

  def search
    
    # params[:page] = 1 if params[:page].nil?
    @quotations = Quotation.order(:created_at).reverse_order
    @quotations = @quotations.where("description ILIKE ?", "%#{params[:q]}%").page(params[:page]).per(12)
    
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quotation
      @quotation = Quotation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quotation_params
      params.require(:quotation).permit(:company_id ,:date, :description, :user_appoved_id, :date_approved, :approved, :published, :pdf, :exam_id,:validity,:total_users, :city_total, :province_total, :m_units_total,:provinces, :mobile_units, :rejected, quotation_items_attributes: [:id, :exam_id, :quotation_id,:city_unit, :province_unit, :m_units_unit, :total_users, :_destroy])
    end

    def get_company
      if params[:company_id]
        @company = Company.find(params[:company_id])
      else
        @company = @quotation.company if @quotation.present?
      end
    end

    def get_users
      @users = current_user.rol == 3 ? User.all : User.where.not(rol: ['3']) 
    end

    def can_edit
      if current_user.rol == 1
        if @quotation.approved
          msj = "No es posible editar, cotización fue aprobada!"
        elsif @quotation.rejected
          msj = "No es posible editar, cotización fue rechazada!"
        else

app/helpers/quotations_helper.rb
module QuotationsHelper
end

app/views/quotations/_quotation_item_fields.html.erb
<div class="q-item nested-fields well">
  <%- select_opts = options_from_collection_for_select(@all_exams, 'id', 'name') %>


  
  <%= f.collection_select(:exam_id, @all_exams, :id, :name, { :prompt => 'Selecione un examen'}, :class => "q-item-select" ) %>

<div class="row">
	<div class="large-6 columns">
	  <div class="row">
	    <div class="large-8 columns">
	      <%= f.label :city_unit, "VU. por ciudad " %>
	    </div>
	    <div class="large-4 columns">
	      <%= f.text_field :city_unit, :class => 'city', :value => number_with_precision(f.object.city_unit,:precision => 2) || 0 %>
	    </div>
	  </div>

	  <div class="row">
	    <div class="large-8 columns">
	      <%= f.label :province_unit, "VU. por provicia " %>
	    </div>
	    <div class="large-4 columns">
	      <%= f.text_field :province_unit, :class => 'province', :value => number_with_precision(f.object.province_unit,:precision => 2) || 0 %>
	    </div>
	  </div>


	  <div class="row">
	    <div class="large-8 columns">
	      <%= f.label :m_units_unit, "VU. por unidades móviles " %>
	    </div>
	    <div class="large-4 columns">
	      <%= f.text_field :m_units_unit , :class => 'mobile' , :value => number_with_precision(f.object.m_units_unit,:precision => 2) || 0%>
	    </div>
	  </div>
	</div>
	<div class="large-6 columns">
	</div>
</div>

  <%= f.hidden_field :quotation_id, :value => @quotation.id %>
  <%= link_to_remove_association "Quitar examen", f %>
</div>

app/views/quotations/edit.html.erb
<%- content_for :title, 'Editar orden' %>
<div class="box">
	<%= render 'form' %>
</div>

app/views/quotations/index.html.erb
<%- if @company.present? %>
  <%- content_for :title, 'Lista de ordenes para: ' + @company.name %>
<%- else %>
  <%- content_for :title, 'Lista de ordenes'%>
<%- end %>



<div class="box row">
  <div class="medium-12 large-12 columns">
    <div class="block table">
      <div class="title-block">
        <h3>Lista de ordenes</h3>
        <div class="right-section">
          <%- if @company.present? %>
            <%- if @company.user_id == current_user.id %>
              <%= link_to 'Nueva cotización', new_company_quotation_path, :class => "small success button" %>
            <%- end %>
          <% end %>
          <%= link_to 'Lista de empresas', companies_path, :class => "small button" %>
        </div>
      </div>
      <div class="content-block">

        <%- unless @filter_by_company.present? %>
          <div class="control-group row">
            <div class="medium-3 large-2 columns">
              <label class="label_select">Filtrar por usuario:</label>
              
            </div>
            <div class="medium-9 large-10 columns">
              <%= select_tag "users", options_from_collection_for_select(@users, "id", "name", @filter_user.present? ? @filter_user.id : ''), include_blank: 'Todos' %>
            </div>
          </div>
        <%end%>
        
        <table class="responsive">
          <thead>
            <tr>
              <th>Descripción</th>
              <th>Empresa</th>
              <th class="date">Creado en</th>
              <th>Total</th>
              <th>Etapa</th>
              <th class="date">Aprobado en</th>
              <!-- <th>Publicado</th> -->
              <th>Aprobador por</th>
              <!-- <th>PDF</th> -->
              <th class="actions">Acciones</th>
            </tr>
          </thead>

          <tbody>
            <% @quotations.each do |quotation| %>
              <%- class_row = "active"%>
              <%- class_row << " success" if quotation.approved %>
              <%- class_row << " warning" if !quotation.approved %>
              <tr class= "<%= class_row%>" >
                <td>
                  <%= link_to quotation.description, @company.present? ? company_quotation_path(@company,quotation) : quotation_path(quotation) %>
                  <%=  %>
                </td>
                <td><%= quotation.company.name if quotation.company %></td>
                <td><%= quotation.created_at.strftime(@date_format) %></td>
                <td><%= "$" + number_with_precision(quotation.total, :precision => 2) || 0  %></td>
                <td><%= quotation.approved ? "Aprobada" : quotation.rejected ? "Rechazada" : "Pendiente" %></td>
                <td><%= quotation.date_approved.strftime(@date_format) if quotation.date_approved %></td>
                <td><%= User.find(quotation.user_appoved_id).name if quotation.user_appoved_id  %></td>
                
                <!-- 
                <%- if quotation.pdf.url %>
                  <td><%= link_to "Abrir PDF",  quotation.pdf.url if quotation.pdf %></td>
                <%- else%>
                  <td>-----</td>
                <%- end%> -->
                <!-- <td><%= quotation.published %></td> -->


                <%- if current_user.rol > 1 %>
                  <td>
                    <%= link_to 'Editar', @company.present? ? edit_company_quotation_path(@company.id,quotation) : edit_quotation_path(quotation), :class => (quotation.approved || quotation.rejected) ? "tiny button disabled" : "tiny button" %>
                    <%- if current_user.rol == 3 %>
                      <%= link_to 'Eliminar', "/quotations/" + quotation.id.to_s , method: :delete, data: { confirm: 'Esta seguro?' }, :class => "destroy tiny button" %>
                    <%- end %>
                  </td>
                <%- else %>  
                  <td>
                    <%- if quotation.company.user.id != current_user.id %>
                      <%= "Creado por: #{quotation.company.user.name}" %>
                    <%- elsif quotation.approved %>
                      <%= link_to 'Imprimir', "/quotations/" + quotation.id.to_s + ".pdf" , method: :get, :class => "destroy tiny button" %>
                    <%- elsif quotation.rejected %>
                      <%= "Cotización rechazada" %>
                    <%- else %>
                      <%= "Cotización pendiente de aprobación" %>
                    <%- end%>
                  </td>
                <%- end %>

              </tr>
            <% end %>
          </tbody>
          <tfoot>
            <tr>
                
              <td colspan="8">
                <span class="total">
                  <%= @quotations.count > 0 ? "Total : #{@quotations.count}" : "Sin resultados" %>  
                </span>
                <%= paginate @quotations %>    
              </td>
            </tr>
            
          </tfoot>
        </table>
      </div>
    </div>
  </div>
</div>
  
</div>

app/views/quotations/new.html.erb
<%- content_for :title, 'Nueva orden' %>
<div class="box">
	<%= render 'form' %>
</div>

	

app/views/quotations/search.html.erb
<%- if @company.present? %>
  <%- content_for :title, 'Buscar cotizaciones para: ' + @company.name %>
<%- else %>
  <%- content_for :title, 'Buscar cotizaciones'%>
<%- end %>



<div class="box row">
  <div class="medium-12 large-12 columns">
    <div class="block table">
      <div class="title-block">
        <h3>Lista de cotizaciones</h3>
        <div class="right-section">
          <%- if @company.present? %>
            <%- if @company.user_id == current_user.id %>
              <%= link_to 'Nueva Cotización', new_company_quotation_path, :class => "small success button" %>
            <%- end %>
          <% end %>
          <%= link_to 'Lista de empresas', companies_path, :class => "small button" %>
        </div>
      </div>
      <div class="content-block">

        <div class="control-group row">
          <div class="medium-3 large-2 columns">
            <label class="label_search">Buscar por:</label>
            
          </div>
          <div class="medium-9 large-10 columns">
            <form action="<%= search_quotations_path %>" method="post" class="navbar-search pull-right">
              <input type="text" name="q" class="search-query typeahead" placeholder="Buscar Cotizaciones" value="<%= params[:q]%>">
            </form>
          </div>
        </div>
        
        <table class="responsive">
          <thead>
            <tr>
              <th>Descripción</th>
              <th>Empresa</th>
              <th>Creado por</th>
              <th class="date">Creado en</th>
              <th>Total</th>
              <th>Aprobado?</th>
              <th class="date">Aprobado en</th>
              <!-- <th>Publicado</th> -->
              <th>Aprobador Por</th>
              <!-- <th>PDF</th> -->
              <th class="actions">Acciones</th>
            </tr>
          </thead>

          <tbody>
            <% @quotations.each do |quotation| %>
              <%- class_row = "active"%>
              <%- class_row << " success" if quotation.approved %>
              <%- class_row << " warning" if !quotation.approved %>
              <tr class= "<%= class_row%>" >
                <td>
                  <%= link_to quotation.description, @company.present? ? company_quotation_path(@company,quotation) : quotation_path(quotation) %>
                  <%=  %>
                </td>
                <td><%= quotation.company.name if quotation.company %></td>
                <td><%= quotation.company.user.name if quotation.company && quotation.company.user %></td>
                <td><%= quotation.created_at.strftime(@date_format) %></td>
                <td><%= "$" + number_with_precision(quotation.total, :precision => 2) || 0  %></td>
                <td><%= quotation.approved ? "Si" : "No" %></td>
                <td><%= quotation.date_approved.strftime(@date_format) if quotation.date_approved %></td>
                <td><%= User.find(quotation.user_appoved_id).name if quotation.user_appoved_id  %></td>
                
                <!-- 
                <%- if quotation.pdf.url %>
                  <td><%= link_to "Abrir PDF",  quotation.pdf.url if quotation.pdf %></td>
                <%- else%>
                  <td>-----</td>
                <%- end%> -->
                <!-- <td><%= quotation.published %></td> -->


                <%- if current_user.rol == 3 %>
                  <td>
                    <%= link_to 'Editar', @company.present? ? edit_company_quotation_path(@company.id,quotation) : edit_quotation_path(quotation), :class => "tiny button" %>
                    <%= link_to 'Eliminar', "/quotations/" + quotation.id.to_s , method: :delete, data: { confirm: 'Esta seguro?' }, :class => "destroy tiny button" %>
                  </td>
                <%- else %>  
                  <td>
                    <%- if quotation.can_edit(current_user) %>
                      <%= link_to 'Editar', @company.present? ? edit_company_quotation_path(@company.id,quotation) : edit_quotation_path(quotation), :class => "tiny button" %>
                      <%= link_to 'Eliminar', "/quotations/" + quotation.id.to_s , method: :delete, data: { confirm: 'Esta seguro?' }, :class => "destroy tiny button" %>
                    <%- else %>
                      <%- if quotation.company.user.id != current_user.id %>
                        <%= "No es posible editar" %>
                      <%- elsif quotation.approved %>
                        <%= "Cotización aprobada" %>
                      <%- elsif quotation.rejected %>
                        <%= "Cotización rechazada" %>
                      <%- end%>
                      
                    <%- end %>
                  </td>
                <%- end %>

                <%- if current_user.rol == 2 %>
                  <td><%= link_to 'Editar',  @company.present? ? edit_company_quotation_path(@company.id,quotation) : edit_quotation_path(quotation) %></td>
                <%- end %>

              </tr>
            <% end %>
          </tbody>
          <tfoot>
            <tr>
                
            <td colspan="9">
                <span class="total">
                  <%= @quotations.count > 0 ? "Total : #{@quotations.count}" : "Sin resultados" %>  
                </span>
                <%= paginate @quotations %>    
              </td>
            </tr>
            
          </tfoot>
        </table>
      </div>
    </div>
  </div>
</div>
  
</div>

app/views/quotations/show.html.erb
<div class="box row">
  <div class="medium-12 large-12 columns">
    <div class="block">
      <div class="title-block">
        <h3>Informacion de cotización</h3>
      </div>
      
      <div class="content-block">
        <p>
          <strong>Descripción:</strong>
          <%= @quotation.description %>
        </p>

        <p>
          <strong>Creado en:</strong>
          <%= @quotation.date.strftime(@date_format) %>
        </p>

        <p>
          <strong>Creado por:</strong>
          <%= @quotation.company.user.name %>
        </p>


        <p>
          <strong>Vigencia:</strong>
          <%= @quotation.validity.present? ? @quotation.validity.strftime(@date_format) : 'No definido' %>
        </p>

        <p>
          <strong>Número de pacientes:</strong>
          <%= @quotation.total_users %>
        </p>

        <p>
          <strong>Etapa:</strong>
          <%= @quotation.approved ? "Aprobada" : @quotation.rejected ? "Rechazada" : "Pendiente" %>
        </p>

        <p>
          <strong>Aprobador por:</strong>
          <%= User.get_name_by_id(@quotation.user_appoved_id) if @quotation.user_appoved_id %>
        </p>

        <p>
          <strong>Fecha de aprobación:</strong>
          <%= @quotation.date_approved.strftime(@date_format) if @quotation.date_approved%>
        </p>

        <hr>
        <p>
          <strong>Resumen totales</strong>
        </p>

        <p>
          <strong>Subtotal por ciudad:</strong>
          <%= "$" + number_with_precision(@quotation.city_total, :precision => 2) || 0  %>
        </p>

        <p>
          <strong>Subtotal por provincia:</strong>
          <%= "$" + number_with_precision(@quotation.province_total, :precision => 2) || 0  %>
        </p>

        <p>
          <strong>Subtotal por unidad movil:</strong>
          <%= "$" + number_with_precision(@quotation.m_units_total, :precision => 2) || 0  %>
        </p>

        

        <p>
          <strong>TOTAL</strong>
          <%= "$" + number_with_precision(@quotation.total, :precision => 2) || 0  %>
        </p>
        

      <!--   <p>
          <strong>Published:</strong>
          <%= @quotation.published %>
        </p>
       -->
        <hr>
        <p>
          <strong>Lista de exámenes</strong>
        </p>
        <% if @quotation.quotation_items.any? %>
          <ul>
            <% @quotation.quotation_items.each do |quotation_item| %>
              <li> <%= quotation_item.exam.name if quotation_item.exam.present? %> </li>
            <% end %>    
          </ul>
        <% else %>
          <p>No se encontraron exámenes</p>
        <% end %>
        <div class="button-actions">
          <% if current_user.rol > 1 %>
            <%= link_to 'Editar',  @company.present? ? edit_company_quotation_path(@company.id,@quotation) : edit_quotation_path(@quotation), :class => "small success button" %>
          <% end %>
          <%= link_to 'Lista de cotizaciones', @company.present? ? company_quotations_path(@company.id) : quotations_path, :class => "small button" %>
        </div>
      </div>
    </div>
  </div>
</div>