config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :laboratories
  resources :receptionists
  resources :doctors
  resources :patients
  resources :tubes
  resources :exams
  resources :companies
  resources :quotations
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'home#index'

  devise_for :users, controller: { registrations: "devise/registrations"}

  get '/home/reset_data' => 'home#reset_data'

  resources :companies do
    resources :quotations
  end

  resources :exams do
    member do
      get 'get_values'
    end
  end

  resources :quotations do
    collection do
      post 'search'
    end
  end

  resources :orders do
    collection do
      post 'search'
    end
  end

  resources :users do
    collection do
      post 'create_seller'
    end
  end

end

app/models/company.rb
class Company < ActiveRecord::Base
	validates :name, :presence => true
	validates_uniqueness_of :name, :message => '%{value} ya fue registrado en el sistema'
	validates :ruc, :presence => true
	validates_uniqueness_of :ruc, :message => '%{value} ya fue registrado en el sistema'
	validates :user_id, :presence => true
	belongs_to :user
	has_many :quotations


	def sector_fullname
		if self.sector.present?
			[["Educación","educacion"],["Financiero","financiero"],["Industrial","industrial"]]  
			if self.sector == "educacion"
				"Educación"
			elsif self.sector == "financiero"
				"Financiero"
			elsif self.sector == "industrial"
				"Industrial"
			else
				"N/A"
			end
		else
			"N/A"
		end
	end

	def enabled_for_new_quotation?
		last_quotation = self.quotations.last
		if last_quotation.present? && last_quotation.approved == false && (last_quotation.rejected == false || last_quotation.rejected == nil)
			false
		else
			true
		end
	end
	
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :get_sector
  # GET /companies
  # GET /companies.json
  def index
    unless current_user.rol == 3
      @companies = Company.where(:user_id => current_user.id).order(created_at: :desc).page(params[:page]).per(20)
    else
      @companies = Company.all.page params[:page]
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
    
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    @company.user_id = current_user.id
    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Empresa creada correctamente.' }
        format.json { render :show, status: :created, location: @company }
      else
        @company.errors.full_messages.each do |error|
          if error.include?('Ruc') && error.include?('ya fue registrado en el sistema')
            company_created = Company.where(:ruc => params[:company][:ruc]).first
            if company_created
              @company.errors[:base] << "El ruc <strong>#{params[:company][:ruc]}</strong> fue registrado por el usuario: <strong>#{company_created.user.name}</strong> (#{company_created.user.email})".html_safe
              @company.errors.messages.delete(:ruc)
            end
          end
          if error.include?('Nombre') && error.include?('ya fue registrado en el sistema')
            company_created = Company.where(:name => params[:company][:name]).first
            if company_created
              @company.errors[:base] << "El nombre <strong>#{params[:company][:name]}</strong> fue registrado por el usuario: <strong>#{company_created.user.name}</strong> (#{company_created.user.email})".html_safe
              @company.errors.messages.delete(:name)
            end
          end
        end
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    @company.user_id = current_user.id
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Empresa actualizada correctamente.' }
        format.json { render :show, status: :ok, location: @company }
      else

        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    if current_user.rol == 1
      respond_to do |format|
        format.html { redirect_to companies_url, alert: 'No es posible eliminar esta empresa.' }
        format.json { head :no_content }
      end
    else
      @company.destroy
      respond_to do |format|
        format.html { redirect_to companies_url, notice: 'Empresa eliminada correctamente.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :ruc, :direcction, :sector, :contact_name, :contact_email, :doctor_name, :doctor_email, :billing_name, :billing_email, :description)
    end

    def get_sector
      @sectors = [["Educación","educacion"],["Financiero","financiero"],["Industrial","industrial"]]
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company, html: { class: 'form-horizontal'})  do |f| %>
  <fieldset class="row">
    <% if @company.errors.any? %>
      <div class="medium-12 large-12 columns">
        <div id="error_explanation">
          <div class="block">
            <div class="title-block error">
              <h3><%= "Atención!" %> </h2>
            </div>
            <div class="content-block">
              <ul class="list-error">
              <% @company.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <div class="medium-12 large-6 columns">
      <div class="block">
        <div class="title-block">
          <h3>Información de empresa</h3>
        </div>
        
        <div class="content-block">
          <legend>Datos empresa</legend>
          <div class="field form-group">
            <%= f.label :name, "Nombre", :class => 'col-lg-2 control-label required' %>
            <div class="col-lg-10">
              <% if @company.created_at.present? && current_user.rol < 3%>
                <%= f.label @company.name, :class => 'form-control disabled-from' %>
              <% else %>
                <%= f.text_field :name, :class => 'form-control' %>
              <% end %>
            </div>
          </div>
          <div class="field form-group">
            <%= f.label :ruc , "Ruc", :class => 'col-lg-2 control-label required' %>
            <div class="col-lg-10">
              <% if @company.created_at.present? && current_user.rol < 3 %>
                <%= f.label @company.ruc, :class => 'form-control disabled-from' %>
              <% else %>
                <%= f.text_field :ruc, :class => 'form-control' %>
              <% end %>
              
            </div>
          </div>
          <div class="field form-group">
            <%= f.label :direcction , "Direccion", :class => 'col-lg-2 control-label' %>
            <div class="col-lg-10">
              <%= f.text_area :direcction, :class => 'form-control', rows: "5" %>
            </div>
          </div>
          <div class="field form-group">
            <%= f.label :description , "Descripcion", :class => 'col-lg-2 control-label' %>
            <div class="col-lg-10">
              <%= f.text_area :description, :class => 'form-control', rows: "5" %>
            </div>
          </div>
          <div class="field form-group">
            <%= f.label :sector , "Sector", :class => 'col-lg-2 control-label' %>
            <div class="col-lg-10">
              <%= select_tag "[company]sector", options_for_select(@sectors, @company.sector), :class => 'form-control', :include_blank => 'Selecionar un sector'%>
            </div>        
          </div>

          <div class="button-actions">
            <%= f.submit "Guardar", :class => "success button from-button", data: { disable_with: "Por favor espera..." } %>
            <%= link_to 'Lista de Empresas', companies_path, :class => "button from-button" %>    
          </div>
          
        </div>
      </div>


    </div>

    <div class="medium-12 large-6 columns">

      <div class="block">
        <div class="title-block">
          <h3>Información de contacto</h3>
        </div>

        <div class="content-block">
          <legend>Contacto empresa</legend>
          <div class="field form-group">
            <%= f.label :contact_name, "Nombre" , :class => 'col-lg-2 control-label' %>
            <div class="col-lg-10">
              <%= f.text_field :contact_name, :class => 'form-control' %>
            </div>
          </div>
          <div class="field form-group">
            <%= f.label :contact_email, "E-mail" , :class => 'col-lg-2 control-label' %>
            <div class="col-lg-10">
              <%= f.email_field :contact_email, :class => 'form-control', :oninvalid => "this.setCustomValidity('Por favor introduzca una dirección de correo eléctronico válida')", :oninput => "setCustomValidity('')" %>
            </div>
          </div>
          <legend>Doctor empresa</legend>
          <div class="field form-group">
            <%= f.label :doctor_name , "Nombre", :class => 'col-lg-2 control-label' %>
            <div class="col-lg-10">
              <%= f.text_field :doctor_name , :class => 'form-control'%>
            </div>
          </div>
          <div class="field form-group">
            <%= f.label :doctor_email, "E-mail" , :class => 'col-lg-2 control-label' %>
            <div class="col-lg-10">
              <%= f.email_field :doctor_email, :class => 'form-control', :oninvalid => "this.setCustomValidity('Por favor introduzca una dirección de correo eléctronico válida')", :oninput => "setCustomValidity('')" %>
            </div>
          </div>
          <legend>Responsable de facturación empresa</legend>
          <div class="field form-group">
            <%= f.label :billing_name, "Nombre" , :class => 'col-lg-2 control-label' %>
            <div class="col-lg-10">
              <%= f.text_field :billing_name, :class => 'form-control' %>
            </div>
          </div>
          <div class="field form-group">
            <%= f.label :billing_email, "E-mail" , :class => 'col-lg-2 control-label' %>
            <div class="col-lg-10">
              <%= f.email_field :billing_email, :class => 'form-control', :oninvalid => "this.setCustomValidity('Por favor introduzca una dirección de correo eléctronico válida')", :oninput => "setCustomValidity('')" %>
            </div>
          </div>
        </div>
      </div>
    </div>

  </fieldset>
<% end %>

app/views/companies/edit.html.erb
<%- content_for :title, 'Editar empresa' %>
<div class="box">
	<%= render 'form' %>
</div>

app/views/companies/index.html.erb
<%- content_for :title, 'Todas tus empresas' %>
<div class="box row">
  <div class="medium-12 large-12 columns">
    <div class="block table">
      <div class="title-block">
        <h3>Lista de empresas</h3>
        <div class="right-section">
          <a href=<%= new_company_path %> class="small success button">Nueva empresa</a>      
        </div>
      </div>
      <div class="content-block">
        <table class="responsive">
          <thead>
            <tr>
              <th>Nombre</th>
              <th class="date">Creado en</th>
              <th>Ruc</th>
              <th>Sector</th>
              <th>Nombre contacto</th>
              <th>Email contacto</th>
              <th class="actions">Acciones</th>
              <th class="actions">Cotizaciones</th>
            </tr>
          </thead>

          <tbody>
            <% @companies.each do |company| %>
              <tr>
                <td><%= link_to company.name, company %></td>
                <td><%= company.created_at.strftime(@date_format) %></td>
                <td><%= company.ruc %></td>
                <td><%= company.sector_fullname %></td>
                <td><%= company.contact_name %></td>
                <td><%= company.contact_email %></td>
                <td>
                  <%= link_to 'Editar', edit_company_path(company), :class => "tiny button" %>
                  <%-if  current_user.rol > 1 %>
                    <%= link_to 'Eliminar', company, method: :delete, data: { confirm: 'Esta seguro?' }, :class => "destroy tiny button" %>
                  <% end %>
                </td>
                <td>
                  <%= link_to 'Nueva', new_company_quotation_path(company.id), :class => company.enabled_for_new_quotation? ? "tiny button" : "tiny button disabled" %>
                  <%= link_to 'Histórico', company_quotations_path(company.id, :history => true), :class => "tiny button" %>
                </td>
              </tr>
            <% end %>
          </tbody>
          <tfoot>
            <tr>
              <td colspan="8">
                <span class="total">
                  <%= @companies.count > 0 ? "Total : #{@companies.count}" : "Sin resultados" %>  
                </span>
                <%= paginate @companies %>  
              </td>
            </tr>
            
          </tfoot>
        </table>
      </div>
    </div>
  </div>


</div>

app/views/companies/new.html.erb
<%- content_for :title, 'Nueva empresa' %>
<div class="box">
	<%= render 'form' %>	
</div>

app/views/companies/show.html.erb
<div class="box row">
  <div class="medium-12 large-12 columns">
    <div class="block">
      <div class="title-block">
        <h3>Información de Empresa</h3>
      </div>
      
      <div class="content-block">
        
        <h4>Información de empresa</h4>
        <hr/>
        <p>
          <strong>Nombre:</strong>
          <%= @company.name %>
        </p>

        <p>
          <strong>Ruc:</strong>
          <%= @company.ruc %>
        </p>

        <p>
          <strong>Dirección:</strong>
          <%= @company.direcction %>
        </p>

        <p>
          <strong>Descripción:</strong>
          <%= @company.description %>
        </p>

        <p>
          <strong>Sector:</strong>
          <%= @company.sector %>
        </p>

        <h4>Información de contacto</h4>
        <hr/>

        <p>
          <strong>Nombre contacto:</strong>
          <%= @company.contact_name %>
        </p>

        <p>
          <strong>Email contacto:</strong>
          <%= @company.contact_email %>
        </p>

        <p>
          <strong>Nombre doctor:</strong>
          <%= @company.doctor_name %>
        </p>

        <p>
          <strong>Email doctor:</strong>
          <%= @company.doctor_email %>
        </p>

        <p>
          <strong>Nombre responsable de facturación:</strong>
          <%= @company.billing_name %>
        </p>

        <p>
          <strong>Email responsable de facturación:</strong>
          <%= @company.billing_email %>
        </p>

        <%- unless current_user.rol == 1 %>
          <hr/>
          <p>
            <strong>Creado por:</strong>
            <%= @company.user.name %>
          </p>
        <% end%>

        <div class="button-actions">
          <%= link_to 'Editar', edit_company_path(@company), :class => "from-button success button" %> 
          <%= link_to 'Nueva cotización', new_company_quotation_path(@company), :class => @company.enabled_for_new_quotation? ? "from-button success button"  : "from-button success button disabled" %>
          <%= link_to 'Lista de empresas', companies_path, :class => "from-button button" %>
        </div>
      </div>
    </div>
  </div>

  
</div>